name: IslandNames
main: me.nonit.islandnames.IslandNames
version: 0.2
description: Set names for IslandCraft
author: Melonking
depend: [IslandCraft,Vault]

commands:
  name:
    description: Name an island!
  island:
    description: Get island info!
    aliases: [ocean,swamp,sea]
  found:
    description: Deprecated.